[package]
name = "openmensa-rs"
version = "0.1.0"
authors = ["Johannes Wünsche <johannes.wuensche97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
surf = { git = "https://github.com/rustasync/surf.git" }
failure = "0.1.6"
serde = { version = "^1.0", features = ["derive"] }
http = "0.1.19"
url = "2.1.0"
serde_urlencoded = "0.6.1"
getset = "0.0.9"
serde_json = "1.0.41"

[dev-dependencies]
tokio = "0.2.0-alpha.6"

